// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SEQ_USERS");

            modelBuilder.Entity("Efluente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaGestoraCptm")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("AREA_GESTORA_CPTM");

                    b.Property<string>("CoordenadaGeografica")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("COORDENADA_GEO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("DiretoriaCptm")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DIRETORIA_CPTM");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("EstacaoCptm")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ESTACAO_CPTM");

                    b.Property<string>("FonteGeradora")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("FONTE_GERADORA");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("LinhaCptm")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("LINHA_CPTM");

                    b.Property<string>("Municipio")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("MUNICIPIO");

                    b.Property<string>("NaturezaPga")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NATUREZA_PGA");

                    b.Property<string>("NomeContratada")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NOME_CONTRATADA");

                    b.Property<string>("NomeLocalAtividade")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NM_LOCAL_ATIVIDADE");

                    b.Property<string>("NumeroContrato")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NUMERO_CONTRATO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<string>("OrigemEfluente")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ORIGEM_EFLUENTE");

                    b.Property<string>("ProgramaAmbiental")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PROGRAMA_AMBIENTAL");

                    b.Property<string>("SiglaDepartamentoMeioAmbiente")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SIGLA_DEPTO_MA");

                    b.Property<string>("StatusDesvioAmbiental")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("STATUS_DESVIO");

                    b.Property<string>("StatusRegistroBd")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("STATUS_REGISTRO_BD");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("SYNC_ID");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SYNC_STATUS");

                    b.Property<string>("TipoAtividade")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("TIPO_ATIVIDADE");

                    b.Property<string>("TipoAtividadeCptm")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("TIPO_ATIVIDADE_CPTM");

                    b.Property<string>("TipoDestinacao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("TIPO_DESTINACAO");

                    b.Property<string>("TipoDra")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("TIPO_DRA");

                    b.Property<string>("TipoVeiculo")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("TIPO_VEICULO");

                    b.Property<string>("TrechoSentido")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("TRECHO_SENTIDO");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("ViaCptm")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("VIA_CPTM");

                    b.HasKey("Id");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.ToTable("PT_EFLUENTE", (string)null);
                });

            modelBuilder.Entity("PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRES_AT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TOKEN");

                    b.Property<int>("Used")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USED");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.ToTable("PASSWORD_RESET_TOKENS", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("IsAdmin")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_ADMIN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.HasKey("Id");

                    b.ToTable("USERS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
