<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="MailKit" Version="4.16.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.7">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>
				runtime; build; native; contentfiles; analyzers; buildtransitive
			</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.7" />
		<PackageReference Include="Oracle.EntityFrameworkCore" Version="8.23.40" />
		<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.4.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Backend.Domain\Backend.Domain.csproj" />
		<ProjectReference Include="..\Backend.Application\Backend.Application.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	
</Project>